home:
    path: /
    controller: App\Controller\HomeController::welcome

register:
    path: /register
    controller: App\Controller\SecurityController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /lougout
    controller: App\Controller\SecurityController::logout

restaurant-detail:
    path: /restaurant/{id}
    controller: App\Controller\RestaurantController::restaurantDetail

add-restaurant:
    path: /admin/add-restaurant
    controller: App\Controller\RestaurantController::addRestaurant

restaurant-detail-admin:
    path: /admin/restaurant/{id}
    controller: App\Controller\RestaurantController::restaurantDetailAdmin