welcome:
    path: /
    controller: App\Controller\HomeController::welcome

home:
    path: /home
    controller: App\Controller\HomeController::home

register:
    path: /register
    controller: App\Controller\SecurityController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /lougout
    controller: App\Controller\SecurityController::logout

restaurant-detail:
    path: /restaurant/{id}
    controller: App\Controller\RestaurantController::restaurantDetail

add-restaurant:
    path: /admin/add-restaurant
    controller: App\Controller\RestaurantController::addRestaurant

restaurant-detail-admin:
    path: /admin/restaurant/{id}
    controller: App\Controller\RestaurantController::restaurantDetailAdmin

add-entree:
    path: /admin/restaurant/{id}/add-entree
    controller: App\Controller\RestaurantController::addEntree

add-plat:
    path: /admin/restaurant/{id}/add-plat
    controller: App\Controller\RestaurantController::addPlat

add-dessert:
    path: /admin/restaurant/{id}/add-dessert
    controller: App\Controller\RestaurantController::addDessert

add-boisson:
    path: /admin/restaurant/{id}/add-boisson
    controller: App\Controller\RestaurantController::addBoisson

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

