home:
    path: /
    controller: App\Controller\HomeController::home

home_filtered:
    path: /filter={filter}
    controller: App\Controller\HomeController::homeFiltered

register:
    path: /register
    controller: App\Controller\SecurityController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /lougout
    controller: App\Controller\SecurityController::logout

restaurant_detail:
    path: /restaurant/{slug}
    controller: App\Controller\RestaurantController::restaurantDetail

add_restaurant:
    path: /admin/add-restaurant
    controller: App\Controller\RestaurantController::addRestaurant

add_type:
    path: /admin/add-type
    controller: App\Controller\RestaurantController::addType

restaurant_detail_admin:
    path: /admin/restaurant/{slug}
    controller: App\Controller\RestaurantController::restaurantDetailAdmin

add_entree:
    path: /admin/restaurant/{slug}/add-entree
    controller: App\Controller\RestaurantController::addEntree

add_plat:
    path: /admin/restaurant/{slug}/add-plat
    controller: App\Controller\RestaurantController::addPlat

add_dessert:
    path: /admin/restaurant/{slug}/add-dessert
    controller: App\Controller\RestaurantController::addDessert

add_boisson:
    path: /admin/restaurant/{slug}/add-boisson
    controller: App\Controller\RestaurantController::addBoisson

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

contact:
    path: /restaurant/{slug}/contact
    controller: App\Controller\RestaurantController::contact

update_restaurant:
    path: /admin/restaurant/{slug}/update
    controller: App\Controller\RestaurantController::updateRestaurant

remove_restaurant:
    path: /admin/restaurant/{slug}/remove
    controller: App\Controller\RestaurantController::removeRestaurant

remove_entree:
    path: /admin/restaurant/{slug_restaurant}/entree/{slug}/remove
    controller: App\Controller\RestaurantController::removeEntree

remove_plat:
    path: /admin/restaurant/{slug_restaurant}/plat/{slug}/remove
    controller: App\Controller\RestaurantController::removePlat

remove_dessert:
    path: /admin/restaurant/{slug_restaurant}/dessert/{slug}/remove
    controller: App\Controller\RestaurantController::removeDessert

remove_boisson:
    path: /admin/restaurant/{slug_restaurant}/boisson/{slug}/remove
    controller: App\Controller\RestaurantController::removeBoisson