home:
    path: /
    controller: App\Controller\HomeController::home

home_filtered:
    path: /filter={filter}
    controller: App\Controller\HomeController::homeFiltered

register:
    path: /register
    controller: App\Controller\SecurityController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /lougout
    controller: App\Controller\SecurityController::logout

restaurant_detail:
    path: /restaurant/{id}
    controller: App\Controller\RestaurantController::restaurantDetail

add_restaurant:
    path: /admin/add-restaurant
    controller: App\Controller\RestaurantController::addRestaurant

restaurant_detail_admin:
    path: /admin/restaurant/{id}
    controller: App\Controller\RestaurantController::restaurantDetailAdmin

add_entree:
    path: /admin/restaurant/{id}/add-entree
    controller: App\Controller\RestaurantController::addEntree

add_plat:
    path: /admin/restaurant/{id}/add-plat
    controller: App\Controller\RestaurantController::addPlat

add_dessert:
    path: /admin/restaurant/{id}/add-dessert
    controller: App\Controller\RestaurantController::addDessert

add_boisson:
    path: /admin/restaurant/{id}/add-boisson
    controller: App\Controller\RestaurantController::addBoisson

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

contact:
    path: /restaurant/{id}/contact
    controller: App\Controller\RestaurantController::contact

update_restaurant:
    path: /admin/restaurant/{id}/update
    controller: App\Controller\RestaurantController::updateRestaurant

remove_restaurant:
    path: /admin/restaurant/{id}/remove
    controller: App\Controller\RestaurantController::removeRestaurant

remove_entree:
    path: /admin/restaurant/{id_restaurant}/entree/{id}/remove
    controller: App\Controller\RestaurantController::removeEntree

remove_plat:
    path: /admin/restaurant/{id_restaurant}/plat/{id}/remove
    controller: App\Controller\RestaurantController::removePlat

remove_dessert:
    path: /admin/restaurant/{id_restaurant}/dessert/{id}/remove
    controller: App\Controller\RestaurantController::removeDessert

remove_boisson:
    path: /admin/restaurant/{id_restaurant}/boisson/{id}/remove
    controller: App\Controller\RestaurantController::removeBoisson