welcome:
    path: /
    controller: App\Controller\HomeController::welcome

home:
    path: /home
    controller: App\Controller\HomeController::home

register:
    path: /register
    controller: App\Controller\SecurityController::register

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /lougout
    controller: App\Controller\SecurityController::logout

restaurant-detail:
    path: /restaurant/{id}
    controller: App\Controller\RestaurantController::form

admin:
    path: /admin
    controller: App\Controller\AdminController::admin

